// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for providing AI-powered voice customization suggestions.
 *
 * It allows users to receive suggestions for voice customization settings (pitch, tone, etc.)
 * based on the characteristics of their uploaded audio.
 *
 * @interface VoiceSuggestionsInput - Input type for the voiceSuggestions function.
 * @interface VoiceSuggestionsOutput - Output type for the voiceSuggestions function.
 * @function voiceSuggestions - A function that takes VoiceSuggestionsInput and returns a Promise of VoiceSuggestionsOutput.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const VoiceSuggestionsInputSchema = z.object({
  audioDataUri: z
    .string()
    .describe(
      'The audio data URI of the uploaded voice sample. Must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.' // Corrected the grammar and added a period at the end
    ),
  voiceDescription: z
    .string()
    .describe('A description of the desired voice characteristics.'),
});
export type VoiceSuggestionsInput = z.infer<typeof VoiceSuggestionsInputSchema>;

const VoiceSuggestionsOutputSchema = z.object({
  suggestedPitch: z
    .number()
    .describe('Suggested pitch adjustment (percentage, e.g., -10 for 10% lower).'),
  suggestedTone:
    z.string().describe('Suggested emotional tone (e.g., angry, excited, calm, sad).'),
  suggestedClarity:
    z.string().describe('Suggested clarity level (e.g., crystal clear, slightly muffled).'),
  suggestedTempo:
    z.number().describe('Suggested tempo adjustment (percentage, e.g. 10 for 10% faster.)'),
});
export type VoiceSuggestionsOutput = z.infer<typeof VoiceSuggestionsOutputSchema>;

export async function voiceSuggestions(
  input: VoiceSuggestionsInput
): Promise<VoiceSuggestionsOutput> {
  return voiceSuggestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'voiceSuggestionsPrompt',
  input: {schema: VoiceSuggestionsInputSchema},
  output: {schema: VoiceSuggestionsOutputSchema},
  prompt: `You are an AI expert in voice cloning and customization. Given the user's audio sample and desired voice description, provide suggestions for voice customization settings.

Audio Sample: {{media url=audioDataUri}}
Desired Voice Description: {{{voiceDescription}}}

Based on the audio sample and desired voice description, provide the following suggestions:

*   suggestedPitch: Suggested pitch adjustment (percentage, e.g., -10 for 10% lower).
*   suggestedTone: Suggested emotional tone (e.g., angry, excited, calm, sad).
*   suggestedClarity: Suggested clarity level (e.g., crystal clear, slightly muffled).
*   suggestedTempo: Suggested tempo adjustment (percentage, e.g. 10 for 10% faster.)

Please provide your suggestions in the requested JSON format.
`,
});

const voiceSuggestionsFlow = ai.defineFlow(
  {
    name: 'voiceSuggestionsFlow',
    inputSchema: VoiceSuggestionsInputSchema,
    outputSchema: VoiceSuggestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
